version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - syou6162
  ignore:
  - dependency-name: python
    versions:
    - 3.10.0a6.pre.slim
    - 3.9.1.pre.slim
